// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace TravelAPI.Solution.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    partial class TravelAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelAPI.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("Review")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Portland",
                            Country = "USA",
                            Rating = 0.0,
                            Review = "its portland its got the ports"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Toronot",
                            Country = "Canada",
                            Rating = 10.0,
                            Review = "maple syrup eh?"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Paris",
                            Country = "France",
                            Rating = 2.0,
                            Review = "baguette "
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Amsterdam",
                            Country = "Netherlands",
                            Rating = 4.7000000000000002,
                            Review = "The original Las Vegas"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "London",
                            Country = "United Kingdom",
                            Rating = 4.5,
                            Review = "This place is a total place to see."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
